apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: b2s3grgqa-nodejs
  janus-idp.io/tekton: b2s3grgqa-nodejs
  backstage.io/kubernetes-id: b2s3grgqa-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: b2s3grgqa-nodejs
resources:
- deployment.yaml
- route.yaml
- service.yaml
